In [2]:
# pip install numpy
import numpy as np

In [8]:
print(type([1, 2, 3]))
print(type((1, 2, 3)))
print(type(np.array([1, 2, 3])))
print(type(np.array((1, 2, 3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [3]:
np.zeros([5, 7])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
np.arange(4,20) # [4, 20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
np.arange(-12,1)

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [31]:
arreglo_pares = np.arange(0, 20, 2)

In [37]:
print(arreglo_pares.size)
print(len(arreglo_pares))
arreglo_tres_dimensiones = np.zeros([2, 3, 4])
print(arreglo_tres_dimensiones.shape)

10
10
(2, 3, 4)


In [38]:
arreglo_pares.reshape(5, 2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [39]:
arreglo_pares.reshape(2, 5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [41]:
arreglo_24 = np.arange(24)
print(arreglo_24)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [43]:
arreglo_24.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [44]:
arreglo_24.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [45]:
arreglo_24.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [46]:
arreglo_24.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [47]:
arreglo_24.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [48]:
arreglo_24.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
arreglo_24.reshape(1 ,24)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [56]:
arreglo_24.reshape(24,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [57]:
arreglo_24.reshape(2,2,6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [58]:
arreglo_24.reshape(2,2,2,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [61]:
a = np.array([10,10,10])
b = np.array([5,5,5])
# suma
a + b

array([15, 15, 15])

In [63]:
# resta
a - b

array([5, 5, 5])

In [64]:
# multiplicación
a * b

array([50, 50, 50])

In [65]:
# divisiones
a / b

array([2., 2., 2.])

In [86]:
c = np.arange(-200,400,20).reshape(5,3,2)
print(c)
print(c.size)

[[[-200 -180]
  [-160 -140]
  [-120 -100]]

 [[ -80  -60]
  [ -40  -20]
  [   0   20]]

 [[  40   60]
  [  80  100]
  [ 120  140]]

 [[ 160  180]
  [ 200  220]
  [ 240  260]]

 [[ 280  300]
  [ 320  340]
  [ 360  380]]]
30


In [88]:
a + c

ValueError: operands could not be broadcast together with shapes (3,) (5,3,2) 

In [91]:
# Mod
a % b

array([0, 0, 0], dtype=int32)

In [93]:
print(a * 10)
print(a + 7)
print(a - 5)
print(a / 3)

[100 100 100]
[17 17 17]
[5 5 5]
[3.33333333 3.33333333 3.33333333]


In [94]:
arreglo_muestra = np.arange(20).reshape(5,2,2)

In [99]:
resp = arreglo_muestra > 5
print(resp)
arreglo_muestra[resp]

[[[False False]
  [False False]]

 [[False False]
  [ True  True]]

 [[ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]]


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [111]:
resp = arreglo_muestra > 5 
print(resp)
arreglo_muestra[resp]

[[[False False]
  [False False]]

 [[False False]
  [ True  True]]

 [[ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]]


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [197]:
resp = arreglo_muestra > 6
resp2 = arreglo_muestra < 14
resp3 = (arreglo_muestra % 2 == 0)
arreglo_muestra[resp & resp2 & resp3]

array([ 8, 10, 12])

In [206]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [207]:
B = np.arange(4,8).reshape(2,2)
B

array([[4, 5],
       [6, 7]])

In [208]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [209]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [242]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [212]:
arreglo_doce.sum()

66

In [213]:
arreglo_doce.max()

11

In [214]:
arreglo_doce.min()

0

In [243]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [244]:
arreglo_doce.reshape(3,2,2).sum(axis=0)
#Suma los elementos en la misma posicion de cada dimension

array([[12, 15],
       [18, 21]])

In [245]:
arreglo_doce.reshape(3,2,2).sum(axis=1)
#Suma los elementos 

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [246]:
arreglo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])